workspace = "off"

[[imports]]
  disable = false                           # default: false
  ignoreConfig = false                      # default: false
  ignoreImports = false                     # default: false
  noMounts = false                          # default: false
  noVendor = false                          # default: false
  path = "codeberg.org/yelosan/hugo-feeds"

[[imports]]
  path = "codeberg.org/yelosan/hugo-shortcodes"

[[imports]]
  path = "codeberg.org/yelosan/hugo-semantic-web"

[[imports]]
  ignoreConfig = true
  ignoreImports = true
  path = "gitlab.com/youronlyone/images"
  # BGN: /way/ images
    [[imports.mounts]]
      source = "way"
      target = "assets/images"
  # END: /way/ images

[[imports]]
  ignoreConfig = true
  ignoreImports = true
  path = "codeberg.org/youronlyone/content"
  # BGN: /way/ content
    #[[imports.mounts]]
    #  source = "content/way/en-ph"
    #  target = "content"
    #  lang = "en"
    [[imports.mounts]]
      source = "content/way/en-ph"
      target = "content"
      lang = "en-ph"
    [[imports.mounts]]
      source = "content/way/ja"
      target = "content"
      lang = "ja"
    [[imports.mounts]]
      source = "content/way/ko"
      target = "content"
      lang = "ko"
  # END: /way/ content

  # BGN: /way/ fill gaps content
    #[[imports.mounts]]
    #  source = "content/way/en-ph"
    #  target = "content"
    #  lang = "ja"
    #[[imports.mounts]]
    #  source = "content/way/en-ph"
    #  target = "content"
    #  lang = "ko"
  # END: /way/ fill gaps content

[[imports]]
  path = "codeberg.org/yelosan/hugo-globals"

[[imports]]
  path = "codeberg.org/youronlyone/defaults"

[[imports]]
  ignoreConfig = true
  ignoreImports = false
  path = "github.com/techmagus/hugo-theme-stack/v3"


# See: https://gohugo.io/hugo-modules/configuration/#module-config-mounts
#   if you add a mounts section you should remove the old staticDir etc. settings.
#   When you add a mount, the default mount for the concerned target root is ignored: be sure to explicitly add it.
  [[mounts]]
    source = "archetypes"
    target = "archetypes"

  [[mounts]]
    source = "assets"
    target = "assets"

  #[[mounts]]
  #  source = "content/en-ph"
  #  target = "content"
  #  lang = "en"                                        # when in multihost / multilang mode
  [[mounts]]
    source = "content/en-ph"
    target = "content"
    lang = "en-ph"                                      # when in multihost / multilang mode
  [[mounts]]
    source = "content/ja"
    target = "content"
    lang = "ja"                                         # when in multihost / multilang mode
  [[mounts]]
    source = "content/ko"
    target = "content"
    lang = "ko"                                         # when in multihost / multilang mode

  [[mounts]]
    source = "data"
    target = "data"

  [[mounts]]
    source = "i18n"
    target = "i18n"

  [[mounts]]
    source = "layouts"
    target = "layouts"

  #[[mounts]]
  #  source = "static/en-ph"
  #  target = "static"
  #  lang = "en"                                        # when in multihost / multilang mode
  [[mounts]]
    source = "static/en-ph"
    target = "static"
    lang = "en-ph"                                      # when in multihost / multilang mode
  [[mounts]]
    source = "static/ja"
    target = "static"
    lang = "ja"                                         # when in multihost / multilang mode
  [[mounts]]
    source = "static/ko"
    target = "static"
    lang = "ko"                                         # when in multihost / multilang mode
