# YourOnly.One: Do not use mainSections, it's conflicting with the hugo-theme-stack theme.
mainSections = ["blog", "posts"]                                             # Hugo default
mainTypes = ["article", "sitepage", "review"]                                                # YourOnly.One

googleTagManager = "GTM-KT65GHZ"
subdir = "way"
rssfull = "true"
faviconcache = "fmgy"
faviconbuster = "TimmieIsMyFate"
jquerycdn = false

### BGN: Structured Data ###
	siteStartYear = "2007"

	description = "We study the set-apart scripture and accept the truth whatever it might be to free ourselves from the lies that were passed down through generations."
	license = "https://im.youronly.one/p/legal-notice/"
	keywords = ["YourOnly.One", "Yuki", "ᜌᜓᜃᜒ"] # Can be overriden per page
	images = ["https://img.youronly.one/works/FlagMenorah-Proto-(CC0).webp", "https://img.youronly.one/works/FlagMenorah-Paleo-(CC0).webp"]
	#copyright = ""
### END: Structured Data ###

### BGN: Theme Settings ###
	#featuredImageField = ""
	rssFullContent = true
	#favicon = ""

	[footer]
		since = "2009"
		#customText = ""

	[dateFormat]
		published = "2006-01-02 15:04:05 MST"
		lastUpdated = "2006-01-02 15:04:05 MST"

	[sidebar]
		emoji = "🛐"
		subtitle = "Be a Berean."
		[sidebar.avatar]
			enabled = true
			local = false
			src = "https://rsc.youronly.one/img/y/Way-Hanukkahns4.svg"

	[article]
		math = false
		toc = true
		readingTime = true
		[article.license]
			enabled = false
			#default = "CHANGE_THIS"             # We do not need this.

	[comments]
		enabled = true
		provider = "disqus"

		[comments.disqusjs]
			shortname = "youronlyone"
			#apiUrl = ""
			#apiKey = ""
			#admin = ""
			#adminLabel = ""

	[widgets]
		#enabled = ["search", "archives", "tag-cloud"]
		enabled = ["search", "series-cloud", "cat-cloud", "tag-cloud"]
		#[widgets.archives]
			#limit = "5"
			#path = "/archives"
		[widgets.seriesCloud]
			limit = "10"
		[widgets.catCloud]
			limit = "10"
		[widgets.tagCloud]
			limit = "10"

	#[opengraph]
		#[opengraph.twitter]
			#site = "YourOnlyOne7"
			#card = "summary_large_image"

	[defaultImage]
		enabled = false
		local = false
		src = "https://rsc.youronly.one/img/y/Way-Hanukkahns4.svg"

		#[defaultImage.opengraph]
			#enabled = true
			#local = false
			#src = "https://rsc.youronly.one/img/y/Way-Hanukkahns4.svg"

	[colorScheme]
		toggle = true
		default = "dark"

	[imageProcessing]
		[imageProcessing.cover]
			enabled = true
		[imageProcessing.content]
			enabled = true
### END: Theme Settings ###

### BGN: Other Settings ###
	[semweb]
		org = "yelosan"

		#issn = ""
		acquirelicensepage = "https://youronly.one/p/legal-notice/"
		copyrightnotice = "Copyleft 🄯 CC-BY-SA 4.0 International by JC John Sese Cuneta"
		credittext = "YourOnly.One (https://youronly.one)"
		datefirstpublished = "2007-04-06"
		isblog = true
		license = "https://youronly.one/p/legal-notice/"
		publisher = "https://yelosan.youronly.one/"
		sameas = [
			"https://fb.com/The-Natsari-Way-102249625073862",
			"https://mastodon.social/@YourOnlyOne",
			"https://pixelfed.social/youronlyone",
			"https://twitter.com/YourOnlyOne7",
			"https://instagram.com/YourOnly.One",
			"https://fb.com/YourOnly.One0"
		]

		[[semweb.persons]]
			person = "yuki"
			#id = ""
			#name = ""ᜌᜓᜃᜒ (Yuki | 雪亮)"
			#url = ""
			#avatar = ""
			#rel = "noopener external nofollow"

	[verify]
		flattr = "4j1gl5"
		naver = "0212955cb24d6e2c67f92be3c7833cae8a98fa8e"
		wot = "06c7ef6e7986586661ef"
		ocs = "c563648adcfa021a0dfd3d3d8f0be64a"
### END: Other Settings ###
