#mainSections = ["blog", "c"]

googleTagManager = "GTM-KT65GHZ"
subdir = "way"
rssfull = "true"
faviconcache = "fmgy"
faviconbuster = "TimmieIsMyFate"
jquerycdn = false

### BGN: Structured Data ###
  siteStartYear = "2009"

  description = "We study the set-apart scripture and accept the truth whatever it might be to free ourselves from the lies that were passed down through generations."
  license = "https://im.youronly.one/p/legal-notice/"
  #issn = ""
  #awards = [""]
  images = ["https://img.youronly.one/works/FlagMenorah-Proto-(CC0).webp"]

  name = "YourOnly.One" # your company name
  primaryauthor = "ᜌᜓᜃᜒ (Yuki ・ 雪亮)" # Used as primary author if no specific is set
  ownerhomepage = "https://youronly.one"
  alternatenames = [ "JC John Sese Cuneta", "Yuki"]
  gender = "https://schema.org/Male"
  knowslanguages = ["en-PH", "fil", "tl-Tglg"]
  nationality = "Filipino"

  copyright = ""
  copyrightnotice = "JC John Sese Cuneta"
  copyrightyear = "2009"      # same as datePublished

  logourl = "https://img.youronly.one/works/FlagMenorah-Proto-(CC0).webp" # Used in structured data as logo url
  keywords = ["YourOnly.One", "Yuki", "ᜌᜓᜃᜒ"] # Can be overriden per page
  imageurl = "https://img.youronly.one/works/FlagMenorah-Proto-(CC0).webp" # Used in structured data as background image

  contact = "" # Primary email address
  phone = "" # Primary phone
  primarylocation = "" # Used as primary location if no specific is set

  color = "#000000"
  pricerange = "" # Used in structured data as price range
### END: Structured Data ###

### BGN: Theme Settings ###
  mainSections = ["blog", "c"]
  featuredImageField = "cover"
  rssFullContent = true
  #favicon = ""

  [footer]
    since = "2009"
    #customText = ""

  [dateFormat]
    published = "2006-01-02 15:04:05 MST"
    lastUpdated = "2006-01-02 15:04:05 MST"

  [sidebar]
    emoji = "🛐"
    subtitle = "Be a Berean."
    [sidebar.avatar]
      enabled = true
      local = false
      src = "https://rsc.youronly.one/img/y/Way-Hanukkahns4.svg"

  [article]
    math = false
    toc = true
    readingTime = true
    [article.license]
      enabled = false
      default = "CHANGE_THIS"             # We do not need this.

  [comments]
    enabled = true
    provider = "disqus"

    [comments.disqusjs]
      shortname = "youronlyone"
      #apiUrl = ""
      #apiKey = ""
      #admin = ""
      #adminLabel = ""

  [widgets]
    #enabled = ["search", "archives", "tag-cloud"]
    enabled = ["search", "tag-cloud"]
    [widgets.archives]
      limit = "5"
      #path = "/archives"
    [widgets.tagCloud]
      limit = "10"

  [opengraph]
    [opengraph.twitter]
      site = "YourOnlyOne7"
      card = "summary_large_image"

  [defaultImage]
    [defaultImage.opengraph]
      enabled = true
      local = false
      src = "https://rsc.youronly.one/img/y/Way-Hanukkahns4.svg"

  [colorScheme]
    toggle = true
    default = "dark"

  [imageProcessing]
    [imageProcessing.cover]
      enabled = true
    [imageProcessing.content]
      enabled = true
### END: Theme Settings ###

### BGN: Other Settings ###
  [author]                                                    # .Param "author.key"
    name = "ᜌᜓᜃᜒ (Yuki ・ 雪亮)"
    email = ""
    homepage = "https://youronly.one"
    rel = "me noopener"
    #rel = "noopener external nofollow"
    avatar = "https://rsc.youronly.one/img/y/Yuki_flag-square-300x.webp"

  [siteowner]
    given_name = "Yahuhanan Yukia"
    middle_name = "Sese"
    family_name = "Cuneta"

  [semweb.publisher]
    name = "YourOnly.One"
    sameas = "https://youronly.one"

  [verify]
    naver = "0212955cb24d6e2c67f92be3c7833cae8a98fa8e"
    wot = "06c7ef6e7986586661ef"
### END: Other Settings ###
